### ISSUE TITLE
Help on Cooperative Learning

### ISSUE THREAD

**Issue by mlamine21** [hcmlab/nova#468]
Hello, 

First thanks for sharing your work the software is great!

I recently discovered Nova and I want to use it for my work. I'm specifically interested by the cooperative learning part. My goal is to automatically annotate a track on annotation files based on existing annotation files with the track already annotated. I already managed to create annotation schemes and datas following the documentation and import them in NOVA. 

My problem is the following : When I try to use the "Complete Current Annotation" button from the "LEARNING" menu, a blank window appears, then after few seconds of processing NOVA crashes. 

Do you know what can be the problem? Do I have to do specific actions before running the "Complete Current Annotation" button? 
I read on the documentation that it required  a trainer template, but the section is not completed on the documentation, where can I get some documentation about it? I also found on the SSI documentation a "trainer template" section. Do I have to learn how to use the SSI framework before using the cooperative learning tool? 

Thanks in advance for your help :)

**Comment by tobiasbaur** [comment]
Hi.  In order to perform the CML Step in general you will need to download and place a few scripts (At this stage they are not yet downloaded in an automated manner, but it's on the list). You find some example files here on git https://github.com/hcmlab/nova/tree/master/bin/cml.

Make sure in the NOVA settings-> Database tab you are pointing the CML directory to the location where you place these files.

Depending on your task, make sure that the type of your stream in the database has the same name as the subfolder.

As an example: if you want to train a model on an audio task, make sure the (Audio) files are of type audio in your database.
Then, extract an audio feature set, e.g. gemaps on all sessions of your database. (Select the audio file from the list and you should see the available featuresets). Extracting takes some time, depending on the set and your machine. This only needs to be done once per corpus.

Them, when you want to perform the cml step, select the extracted features, select a model (e.g. linsvm) and then it should work.

If you want to use tensorflow, please make sure you installed the python tools and enabled python. It is also recommended to install CUDA on your system, which is system dependent. (But for performing CML I recommend using faster models like linsvm).

I hope this helps,
Tobias

**Comment by mlamine21** [comment]
Hello,
Thanks for your answer it is really helpful.
I am going to try all this and let you know when it comes together (or not). 
I just have one more question. Is it possible to create empty annotation blocks and let the software decide of their values? Or does the machine automatically detect when an annotation should be here.
Let me give some details to understand what I want to do : My goal is to annotate the evaluation of an event made by an agent (e.g. is this event pleasant for the agent? ). I have facial expressions, gaze, speech and temporal signals already annotated. I want to see if it is possible that the machine infers the evaluation based on the annotated signals. I already manually annotated some evaluations, but I want the software to complete these annotations based on what is already annotated. 

Thank you very much for your time,
Best,
Amine
